import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import Navigation from '@/components/general/Navigation';
import SideBar from '@/components/general/SideBar';

const font = Nunito({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: 'Climb | All notes in one place!',
    template: '%s | Climb',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} antialiased min-h-screen`}>
        <main className='grid grid-cols-[20rem_1fr] grid-rows-[6rem_1fr] min-h-screen bg-gray-900'>
          <Navigation />
          <SideBar />
          {children}
        </main>
      </body>
    </html>
  );
}
